spring.application.name=InstituteManagement
server.port = 8085

spring.datasource.url=jdbc:postgresql://ep-twilight-water-ap3xzlc5-pooler.c-7.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_3cYDyQLpMs8k&sslmode=require&channelBinding=require


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
